fn main() {
    // 1. Compile ga3d C++ core as a static library
    let dst = cmake::Config::new("../")
        .define("GA3D_BUILD_TESTS", "OFF")
        .build();

    // 2. Instruct Cargo where to find the static library
    println!("cargo:rustc-link-search=native={}/lib", dst.display());
    println!("cargo:rustc-link-lib=static=ga3d_core");

    // 3. Link C++ core dependencies
    println!("cargo:rustc-link-lib=dylib=webp");
    println!("cargo:rustc-link-lib=dylib=z");

    // 4. Compile FFI bridge generated by cxx
    cxx_build::bridge("src/bridge.rs")
        .include("../") // parent dir containing core/include
        .flag_if_supported("-std=c++20")
        .compile("ga3d_bridge");

    // 5. Build Tauri application
    tauri_build::build();
}
